swagger: "2.0"
info:
  description: "Este API se utiliza para el registro de jugadores de una escuela de futbol"
  version: "1.0.0"
  title: "los_galacticos_fc_api_v1"
  contact:
    email: "verovergaravaldez@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost"
basePath: "/v1"
tags:
- name: "player"
  description: "Player managment"
- name: "FootballScholl"
  description: "FootballScholl managment"
schemes:
- "http"
paths:
  /player:
    post:
      tags:
      - "player"
      summary: "Add a new player"
      description: ""
      operationId: "addPlayer"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Data of the new player"
        required: true
        schema:
          $ref: "#/definitions/Player"
      responses:
        "201":
          description: "created"
          schema:
            $ref: "#/definitions/SuccessResponse"
        "400":
          description: "Bad request"
          schema:
            $ref: "#/definitions/ErrorResponse"
        "500":
          description: "Internal server error"
          schema:
            $ref: "#/definitions/ErrorResponse"
    get:
      tags:
      - "player"
      summary: "Get a list of players"
      description: ""
      operationId: "getPlayers"
      produces:
      - "application/json"
      parameters:
      - name: "ciudad"
        in: "query"
        description: "The city of the player"
        required: false
        type: "string"
      - name: "categoria"
        in: "query"
        description: "The category of the player"
        required: false
        type: "string"
      - name: "inspeccionMedica"
        in: "query"
        description: "Medical inspection of the player"
        required: false
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Player"
        "400":
          description: "Bad request"
          schema:
            $ref: "#/definitions/ErrorResponse"
        "500":
          description: "Internal server error"
          schema:
            $ref: "#/definitions/ErrorResponse"
  /player/{cedula}:
    get:
      tags:
      - "player"
      summary: "Get a player"
      description: ""
      operationId: "getOnePlayer"
      produces:
      - "application/json"
      parameters:
      - name: "cedula"
        in: "path"
        description: "Player's id"
        required: true
        type: "integer"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Player"
        "400":
          description: "Bad request"
          schema:
            $ref: "#/definitions/ErrorResponse"
        "500":
          description: "Internal server error"
          schema:
            $ref: "#/definitions/ErrorResponse"
    put:
      tags:
      - "player"
      summary: "Update a player"
      description: ""
      operationId: "updatePlayer"
      produces:
      - "application/json"
      parameters:
      - name: "cedula"
        in: "path"
        description: "Player's id"
        required: true
        type: "integer"
      - in: "body"
        name: "body"
        description: "Data of the updated player"
        required: true
        schema:
          $ref: "#/definitions/PlayerUpdate"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Player"
        "400":
          description: "Bad request"
          schema:
            $ref: "#/definitions/ErrorResponse"
        "500":
          description: "Internal server error"
          schema:
            $ref: "#/definitions/ErrorResponse"
    delete:
      tags:
      - "player"
      summary: "Delete a player"
      description: ""
      operationId: "DeletePlayer"
      produces:
      - "application/json"
      parameters:
      - name: "cedula"
        in: "path"
        description: "Player's id"
        required: true
        type: "integer"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/SuccessResponse"
        "400":
          description: "Bad request"
          schema:
            $ref: "#/definitions/ErrorResponse"
        "500":
          description: "Internal server error"
          schema:
            $ref: "#/definitions/ErrorResponse"
definitions:
  Player:
    type: "object"
    properties:
      nombre:
        type: "string"
      apellido:
        type: "string"
      edad:
        type: "integer"
      categoria:
        type: "string"
      nacionalidad:
        type: "string"
      ciudad:
        type: "string"
      ci:
        type: "string"
      celular:
       type: "string"
      inspeccionMedica:
        type: "string"
  PlayerUpdate:
    type: "object"
    properties:
      nombre:
        type: "string"
      apellido:
        type: "string"
      edad:
        type: "integer"
      categoria:
        type: "string"
      ciudad:
        type: "string"
      inspeccionMedica:
        type: "string"
  SuccessResponse:
    type: "object"
    properties:
      message:
        type: "string"
      code:
        type: "integer"
  ErrorResponse:
    type: "object"
    properties:
      error:
        type: "integer"
      message:
        type: "string"
      detail:
        type: "string"
